workflows:
  android:
    name: Build Android App
    flutter: stable  # 使用するFlutterのバージョンを指定 (例: stable, 3.x.x)
    scripts:
      - flutter clean  # ビルドキャッシュをクリア
      - flutter pub get  # 依存関係を取得
      - flutter build appbundle --release  # アプリのリリースビルド

  ios_release:
    name: iOS release workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      ios: latest
    scripts:
      # Step 1: Flutterの依存関係をインストール
      - flutter-install:
          channel: stable

      # Step 2: CocoaPodsの依存関係をインストール
      - run:
          name: Install CocoaPods dependencies
          command: |
            cd ios
            pod install  # CocoaPodsの依存関係をインストール

      # Step 3: iOSアプリをビルド
      - flutter-build:
          ios: true
          release: true

      # Step 4: App Store Connectへのアップロード (オプション)
      - app-store-connect-publish:
          api_key_id: XGA9N225C9
          api_issuer_id: dda28ccc-233f-43ba-8a3c-c77009e75e27
          private_key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGA1EydJ99HFfbSQuv/LazS+R+3Hp8JSWNI3xX0zg+QSgCgYIKoZIzj0DAQehRANCAAQdRgd7qRp09bCXcJk2FiFst+vDtazwBi3heYZDwP0wz8waS70j2W8GCXC7YpVdxxgxuvUyKBhLC1eQGNoDqOXX
          ipa_path: build/ios/ipa/まじっくくれぱす.ipa

      # Step 5: Git操作とGitHubへのコミット（任意）
      - run:
          name: Initialize CocoaPods and Git commit
          command: |
            cd ios
            # Initialize CocoaPods (if not already initialized)
            if [ ! -f Podfile ]; then
              pod init
            fi
            # Stage all changes in the git repository
            git add .
            git commit -m "Added Podfile"
            git push

    ios:
      # Provide the necessary iOS-specific build configurations
      code_signing_identity: iPhone Developer
      export_method: ad-hoc
      provisioning_profile_path: /path/to/provisioning/profile
      development_team: P8RMNG2P8Z
